
platform :ios, '8.0'
use_frameworks!

target 'KZWFoundation-Swift' do

   pod 'RxSwift'
   pod 'RxCocoa'
   pod 'Alamofire'
   pod 'SwiftyJSON'
   pod 'SnapKit'
   pod 'SVProgressHUD'
   pod 'Kingfisher'
   pod 'MJRefresh'
   pod 'Reusable'
   pod 'JPush'

  end

  target 'KZWFoundation-SwiftTests' do

  end

  target 'KZWFoundation-SwiftUITests' do

  end
